**Let's Learn Numpy**

In [74]:
import numpy as np
from mpmath import zeros

In [75]:
print("Let's Make some Graph")

Let's Make some Graph


In [76]:
myarr = np.array([[2, 5, 78, 6]], np.int64)

In [77]:
myarr[0, 1]

np.int64(5)

In [78]:
myarr.shape

(1, 4)

In [79]:
myarr.size

4

In [80]:
myarr.dtype

dtype('int64')

In [81]:
myarr[0, 1] = 25

In [82]:
myarr

array([[ 2, 25, 78,  6]])

*Array creation: Conversion from other Python structures*

In [83]:
listarray = np.array([[1, 2, 4, 6, 7], [2, 4, 5, 6, 8]])

In [84]:
listarray.dtype

dtype('int64')

In [85]:
listarray.shape

(2, 5)

In [86]:
listarray.size

10

In [87]:
np.array({23,54,99})

array({99, 54, 23}, dtype=object)

In [88]:
zeros = np.zeros((2, 5))

In [89]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
zeros.dtype

dtype('float64')

In [91]:
zeros.shape

(2, 5)

In [92]:
rng = np.arange(16)

In [93]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
lspace = np.linspace(1,50,100)

In [95]:
lspace

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [96]:
lspace1 = np.linspace(1,4,4)

In [97]:
lspace1

array([1., 2., 3., 4.])

In [98]:
lspace2 = np.linspace(1,5,4)

In [99]:
lspace2

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [100]:
ide = np.identity(45)

In [101]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [102]:
ide.shape

(45, 45)

In [103]:
emp_like = np.empty_like(lspace1)

In [104]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [105]:
ide = np.identity(99)

In [106]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [107]:
ide.shape

(99, 99)

In [108]:
arr = np.arange(99)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [110]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [112]:
arr = arr.ravel()

In [113]:
arr.shape

(99,)

In [114]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [115]:
ar = np.array(x)

In [116]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [117]:
ar.sum(axis=0)

array([12,  8,  9])

In [118]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [119]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [120]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [121]:
ar.ndim

2

In [122]:
ar.size

9

In [123]:
ar.nbytes

72

In [124]:
one = np.array([1,3,4,63,8,6,3])

In [125]:
one.argmax()

np.int64(3)

In [126]:
 one.argmin()

np.int64(0)

In [127]:
one.argsort()

array([0, 1, 6, 2, 5, 4, 3])

In [128]:
ar.argmin()

np.int64(8)

In [129]:
ar.argmax()

np.int64(6)

In [130]:
ar.argmax(axis=0)

array([2, 1, 1])

In [131]:
ar.argmax(axis=1)

array([2, 2, 0])

In [132]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [133]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [134]:
ar2 = np.array([[1,2,1],
               [4,0,6],
               [8,1,0]])

In [135]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [136]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [137]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [138]:
ar.sum()

np.int64(29)

In [139]:
ar.max()

np.int64(7)

In [140]:
ar.min()

np.int64(0)

In [141]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [142]:
np.count_nonzero(ar)

8

In [143]:
np.count_nonzero(ar)

8

In [144]:
ar[1,2] = 0

In [145]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [146]:
np.count_nonzero(ar)

7

In [149]:
import sys

In [150]:
py_ar = [0,4,55,2]

In [151]:
np_ar = np.array(py_ar)

In [152]:
sys.getsizeof(1) * len(py_ar)

112

In [153]:
np_ar.itemsize * np_ar.size

32