**Let's Learn Numpy**

In [109]:
import numpy as np
from mpmath import zeros

In [110]:
print("Let's Make some Graph")

Let's Make some Graph


In [111]:
myarr = np.array([[2, 5, 78, 6]], np.int64)

In [112]:
myarr[0, 1]

np.int64(5)

In [113]:
myarr.shape

(1, 4)

In [114]:
myarr.size

4

In [115]:
myarr.dtype

dtype('int64')

In [116]:
myarr[0, 1] = 25

In [117]:
myarr

array([[ 2, 25, 78,  6]])

*Array creation: Conversion from other Python structures*

In [118]:
listarray = np.array([[1, 2, 4, 6, 7], [2, 4, 5, 6, 8]])

In [119]:
listarray.dtype

dtype('int64')

In [120]:
listarray.shape

(2, 5)

In [121]:
listarray.size

10

In [122]:
np.array({23,54,99})

array({99, 54, 23}, dtype=object)

In [123]:
zeros = np.zeros((2, 5))

In [124]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [125]:
zeros.dtype

dtype('float64')

In [126]:
zeros.shape

(2, 5)

In [127]:
rng = np.arange(16)

In [128]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [129]:
lspace = np.linspace(1,50,100)

In [130]:
lspace

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [131]:
lspace1 = np.linspace(1,4,4)

In [132]:
lspace1

array([1., 2., 3., 4.])

In [133]:
lspace2 = np.linspace(1,5,4)

In [134]:
lspace2

array([1.        , 2.33333333, 3.66666667, 5.        ])